### ISSUE TITLE
Content EveryDay in Sep 

### ISSUE THREAD

**Issue by travelcookies** [RocAndTrees/UsUpdata#8]
每日除了工作以外的记录，记录事情。

**Comment by travelcookies** [comment]
date ：9-1 周五

* 读书
把时间当作朋友 第五章
 * 健康
两次早晚 OK

**Comment by travelcookies** [comment]
date ：9-4 周一

* 读书
把时间当作朋友 第五章
* 健康
两次早晚 OK

**Comment by travelcookies** [comment]
date ：9-5 周二

* 读书
把时间当作朋友 第五章
* 健康
 早  OK
人祸：十字路口四轮车碰着了

**Comment by travelcookies** [comment]
date ：9-6 周三

* 读书
把时间当作朋友 第五章
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-7 周四

* 读书
把时间当作朋友 第六章
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-10 周日

* 读书
把时间当作朋友 第七章
* 健康
 早晚  OK
* 运动
40分钟

**Comment by travelcookies** [comment]
date ：9-11 周一

* 读书
把时间当作朋友 第八章 完结
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-12 周二

* 读书
浪潮之巅 上 3章
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-13 周三

* 读书
浪潮之巅 上 5章
iOS anmiation 第一章
* 健康
 早晚  OK
* 运动
40分钟

**Comment by travelcookies** [comment]
date ：9-14 周四

* 读书
浪潮之巅 上  2个 tomato
iOS anmiation 1个tomato
* 健康
 早晚  OK
* 运动
40分钟

**Comment by RocAndTrees** [comment]
date ：9-14 周四

* 读书
浪潮之巅 上  2个 tomato
iOS anmiation 1个tomato
* 健康
 早晚  OK
* 运动
40分钟

**Comment by travelcookies** [comment]
date ：9-15 周五

* 读书
iOS anmiation 1个tomato
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-18 周一
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-19 周二

* 读书
iOS anmiation 0.5个tomato
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-19 周三

* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-21 周四

* 读书
浪潮之巅 上 2.5个tomato
* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-24 周日

* 读书
浪潮之巅 上 3个tomato

**Comment by travelcookies** [comment]
date ：9-25 周一

* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-26 周二

* 健康
 早晚  OK
* 学习
boxue 1

**Comment by travelcookies** [comment]
date ：9-27 周三

* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-28 周四

* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-29 周五

* 健康
 早晚  OK

**Comment by travelcookies** [comment]
date ：9-30 周六

* 健康
 早 OK
* 读书
30分钟
